using internals.autogenerated;
using internals.errors;
using internals.lox;
using internals.token;

using Nothing = object;

namespace internals.interpreter {
    class Interpreter : Expr.IVisitor<object>, Stmt.IVisitor<Nothing> {
        private environment.Environment environment = new();
        public bool isInREPL = false;
        public void Interpret(List<Stmt> statements) {
            try {
                foreach (var statement in statements) {
                    Execute(statement);
                }
            } catch (RuntimeError error) {
                Lox.RuntimeError(error);
            }
        }
        public string Interpret(Expr expr) {
            try {
                object value = Evaluate(expr);
                return Stringify(value);
            } catch (RuntimeError error) {
                Lox.RuntimeError(error);
                return null;
            }
        }
        public object VisitLiteralExpr(Expr.Literal expr) {
            return expr.value;
        }
        public object VisitGroupingExpr(Expr.Grouping expr) {
            return Evaluate(expr.expression);
        }
        public object VisitUnaryExpr(Expr.Unary expr) {
            object right = Evaluate(expr.right);

            switch (expr.operatorToken.type) {
                case TokenType.MINUS: {
                    CheckNumberOperand(expr.operatorToken, right);
                    return -(double)right;
                }
                case TokenType.BANG: {
                    return !IsTruthy(right);
                }
            }

            // Unreachable
            return null;
        }

        public object VisitBinaryExpr(Expr.Binary expr) {
            object left = Evaluate(expr.left);
            object right = Evaluate(expr.right);

            switch (expr.operatorToken.type) {
                // Arithmetic
                case TokenType.PLUS: {
                    if (left is double && right is double) {
                        return (double)left + (double)right;
                    }

                    if (left is string && right is string) {
                        return (string)left + (string)right;
                    }

                    if (left is string && right is double) {
                        return (string)left + ((double)right).ToString();
                    }

                    if (left is double && right is string) {
                        return ((double)left).ToString() + (string)right;
                    }

                    throw new RuntimeError(expr.operatorToken, "Operands must be two numbers or two strings.");
                }
                case TokenType.MINUS: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left - (double)right;
                }
                case TokenType.SLASH: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    if ((double)right == 0) throw new RuntimeError(expr.operatorToken, "Division by zero.");
                    return (double)left / (double)right;    
                }
                case TokenType.STAR: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left * (double)right;    
                }

                // Comparison
                case TokenType.GREATER: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left > (double)right;
                }
                case TokenType.GREATER_EQUAL: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left >= (double)right;
                }
                case TokenType.LESS: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left < (double)right;
                }
                case TokenType.LESS_EQUAL: {
                    CheckNumberOperands(expr.operatorToken, left, right);
                    return (double)left <= (double)right;
                }
                case TokenType.BANG_EQUAL: {
                    return !IsEqual(left, right);
                }
                case TokenType.EQUAL_EQUAL: {
                    return IsEqual(left, right);
                }
            }

            // Unreachable
            return null;
        }
        public object VisitVariableExpr(Expr.Variable expr) {
            return environment.Get(expr.name);
        }
        public object VisitAssignExpr(Expr.Assign expr) {
            object value = Evaluate(expr.value);
            environment.Assign(expr.name, value);
            return value;
        }
        public Nothing VisitBlockStmt(Stmt.Block stmt) {
            ExecuteBlock(stmt.statements, new environment.Environment(environment));
            return null;
        }
        public Nothing VisitExpressionStmt(Stmt.Expression stmt) {
            Evaluate(stmt.expression);
            return null;
        } 
        public Nothing VisitPrintStmt(Stmt.Print stmt) {
            object value = Evaluate(stmt.expression);
            Console.WriteLine(Stringify(value));
            return null;
        } 
        public Nothing VisitVarStmt(Stmt.Var stmt) {
            object value = null;
            if (stmt.intializer != null) {
                value = Evaluate(stmt.intializer);
            }

            environment.Define(stmt.name.lexeme, value);
            return null;
        }
        private void ExecuteBlock(List<Stmt> statements, environment.Environment environment) {
            environment.Environment previous = this.environment;
            try {
                this.environment = environment;

                foreach (Stmt statement in statements) {
                    Execute(statement);
                }
            } finally {
                this.environment = previous;
            }
        }
        private bool IsTruthy(object obj)
        {
            if (obj == null) return false;
            if (obj is bool) return (bool)obj;
            return true;
        }
        private bool IsEqual(object left, object right)
        {
            if (left == null && right == null) return true;
            if (left == null) return false;
            return left.Equals(right);
        }
        private object Evaluate(Expr expr) {
            object value = expr.Accept(this);
            return value;
        }
        private void CheckNumberOperand(Token operatorToken, object operand)
        {
            if (operand is double) return;
            throw new RuntimeError(operatorToken, "Operand must be a number.");
        }
        private void CheckNumberOperands(Token operatorToken, object left, object right) {
            if (left.GetType() == typeof(double) && right.GetType() == typeof(double)) return;
    
            throw new RuntimeError(operatorToken, "Operands must be numbers.");
        }
        private string Stringify(object obj) {
            if (obj == null) return "nil";

            string text = obj.ToString();
            if (obj is double && text.EndsWith(".0")) {
                text = text[0..(text.Length - 2)];
            }

            return text;
        }
        private void Execute(Stmt stmt) {
            stmt.Accept(this);
        }
    }
}